GET http://localhost:3003/api/blogs/

###
GET http://localhost:3003/api/blogs/67d752406141032ccd03ee93

###
DELETE http://localhost:3003/api/blogs/67d752266141032ccd03ee8e

###
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
  "title": "Test3",
  "author": "testRequest",
  "url": "test.com",
  "likes": 3
}

###
# PUT http://localhost:3003/api/blogs/3
# Content-Type: application/json

# {
#   "title": "Test",
#   "author": "testRequest",
#   "url": "test.com",
#   "likes": 0
# }

###

