GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/5c41c90e84d891c15dfa3431

###
DELETE http://localhost:3001/api/persons/67d2ef93b8542354270ad302

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Test Person",
  "number": "123-456-7890"
}

###
PUT http://localhost:3001/api/persons/67d3672039c0405be240589b
Content-Type: application/json

{
  "name": "Test Person",
  "number": "123-456-7890"
}

###

